import {
  EndpointHealthResponse,
  FailureFingerprintResponse,
  MetricResponse,
  OverviewResponse,
  RecommendationResponse,
  ReplayAnalysisResponse,
  RetryOptimizationResponse,
  WebhookEventResponse,
} from "./types";

export const mockOverviewResponse: OverviewResponse = {
  metrics: [
    {
      key: "total_events",
      title: "Total Events",
      value: 1240000,
      change: 6.2,
      trend: "up",
      tone: "info",
    },
    {
      key: "delivered_rate",
      title: "Delivered %",
      value: 94.6,
      unit: "%",
      change: 1.1,
      trend: "up",
      tone: "success",
    },
    {
      key: "failed_rate",
      title: "Failed %",
      value: 3.4,
      unit: "%",
      change: -0.8,
      trend: "down",
      tone: "warning",
    },
    {
      key: "recovered_rate",
      title: "Recovered %",
      value: 1.7,
      unit: "%",
      change: 0.3,
      trend: "up",
      tone: "success",
    },
    {
      key: "replay_safe",
      title: "Replay Safe %",
      value: 91.2,
      unit: "%",
      change: 2.1,
      trend: "up",
      tone: "info",
    },
    {
      key: "critical_endpoints",
      title: "Critical Endpoints",
      value: 8,
      change: 2,
      trend: "up",
      tone: "danger",
    },
  ],
  delivery_distribution: [
    { name: "Delivered", value: 74 },
    { name: "Failed", value: 12 },
    { name: "Recovered", value: 9 },
    { name: "Queued", value: 5 },
  ],
  failure_trend: [
    { time: "00:00", failed: 42, recovered: 18 },
    { time: "03:00", failed: 55, recovered: 21 },
    { time: "06:00", failed: 38, recovered: 20 },
    { time: "09:00", failed: 70, recovered: 34 },
    { time: "12:00", failed: 62, recovered: 28 },
    { time: "15:00", failed: 48, recovered: 24 },
    { time: "18:00", failed: 58, recovered: 30 },
    { time: "21:00", failed: 66, recovered: 35 },
  ],
  endpoint_health_overview: [
    { name: "Billing API", score: 92 },
    { name: "CRM Hub", score: 77 },
    { name: "Payments", score: 64 },
    { name: "Inventory", score: 71 },
    { name: "Identity", score: 84 },
  ],
  replay_confidence_distribution: [
    { band: "Safe", value: 62 },
    { band: "Duplicate Risk", value: 21 },
    { band: "Unsafe", value: 17 },
  ],
  retry_pattern_stats: [
    { pattern: "timeout → timeout → success", count: 142 },
    { pattern: "429 → 429 → 200", count: 96 },
    { pattern: "401 → 401 → 401", count: 44 },
    { pattern: "500 → 500 → 200", count: 68 },
  ],
};

export const mockEventsResponse: WebhookEventResponse[] = [
  {
    id: "evt_10942",
    type: "invoice.paid",
    endpoint_id: "ep_01",
    delivery_state: "Recovered",
    failure_reason: "timeout",
    replay_confidence: {
      score: 88,
      reasons: ["Short retry chain", "Endpoint stable", "Low duplicate risk"],
      duplicate_risk: 12,
    },
    endpoint_health: {
      score: 92,
      reasons: ["High success rate", "Low timeout frequency"],
    },
    recommended_action: "Retry after cooldown",
    timestamp: "2026-05-16 09:12:03",
    retry_pattern: ["timeout", "timeout", "success"],
    attempts: [
      { time: "09:09", status: "timeout", latency_ms: 12000 },
      { time: "09:10", status: "timeout", latency_ms: 12000 },
      { time: "09:12", status: "200", latency_ms: 820 },
    ],
  },
  {
    id: "evt_10943",
    type: "subscription.updated",
    endpoint_id: "ep_07",
    delivery_state: "Failed",
    failure_reason: "401 unauthorized",
    replay_confidence: {
      score: 24,
      reasons: ["Repeated signature failures", "Endpoint unstable"],
      duplicate_risk: 31,
    },
    endpoint_health: {
      score: 49,
      reasons: ["High failure streak", "Increased latency"],
    },
    recommended_action: "Fix endpoint configuration",
    timestamp: "2026-05-16 09:13:48",
    retry_pattern: ["401", "401", "401"],
    attempts: [
      { time: "09:11", status: "401", latency_ms: 430 },
      { time: "09:12", status: "401", latency_ms: 450 },
      { time: "09:13", status: "401", latency_ms: 470 },
    ],
  },
  {
    id: "evt_10944",
    type: "payment.failed",
    endpoint_id: "ep_11",
    delivery_state: "Failed",
    failure_reason: "rate limited",
    replay_confidence: {
      score: 46,
      reasons: ["Rate limit cluster detected", "Moderate duplicate risk"],
      duplicate_risk: 38,
    },
    endpoint_health: {
      score: 61,
      reasons: ["Timeout frequency rising", "Latency above baseline"],
    },
    recommended_action: "Retry after 10 minutes",
    timestamp: "2026-05-16 09:16:05",
    retry_pattern: ["429", "429", "200"],
    attempts: [
      { time: "09:14", status: "429", latency_ms: 210 },
      { time: "09:15", status: "429", latency_ms: 215 },
      { time: "09:16", status: "200", latency_ms: 980 },
    ],
  },
  {
    id: "evt_10945",
    type: "charge.refunded",
    endpoint_id: "ep_05",
    delivery_state: "Delivered",
    failure_reason: "-",
    replay_confidence: {
      score: 97,
      reasons: ["Single success attempt", "Endpoint healthy"],
      duplicate_risk: 6,
    },
    endpoint_health: {
      score: 95,
      reasons: ["Stable latency", "No active failures"],
    },
    recommended_action: "No action needed",
    timestamp: "2026-05-16 09:20:45",
    retry_pattern: ["200"],
    attempts: [{ time: "09:20", status: "200", latency_ms: 620 }],
  },
];

export const mockEndpointsResponse: EndpointHealthResponse[] = [
  {
    endpoint_id: "ep_01",
    name: "Billing API",
    score: 92,
    success_rate: 98.2,
    failure_streak: 0,
    avg_latency_ms: 420,
    timeout_frequency: 0.8,
    status: "Healthy",
    reasons: ["High success rate", "Low timeout frequency"],
  },
  {
    endpoint_id: "ep_05",
    name: "Identity",
    score: 84,
    success_rate: 95.6,
    failure_streak: 1,
    avg_latency_ms: 510,
    timeout_frequency: 1.2,
    status: "Healthy",
    reasons: ["Stable response times", "Minimal failure streak"],
  },
  {
    endpoint_id: "ep_07",
    name: "CRM Hub",
    score: 61,
    success_rate: 87.4,
    failure_streak: 3,
    avg_latency_ms: 820,
    timeout_frequency: 3.4,
    status: "Unstable",
    reasons: ["Increased latency", "Failure streak present"],
  },
  {
    endpoint_id: "ep_11",
    name: "Payments",
    score: 49,
    success_rate: 73.9,
    failure_streak: 6,
    avg_latency_ms: 1240,
    timeout_frequency: 7.1,
    status: "Critical",
    reasons: ["Timeout frequency high", "Low success rate"],
  },
];

export const mockFingerprintsResponse: FailureFingerprintResponse[] = [
  {
    id: "fp_rate_limit",
    label: "RATE_LIMIT_CLUSTER",
    sequence: "429 → 429 → 200",
    recovery_rate: 82,
    avg_retries: 2.3,
    dominant_cause: "Burst throttling",
    replay_safety: 78,
    action: "Retry after cooldown",
  },
  {
    id: "fp_timeout",
    label: "TIMEOUT_CLUSTER",
    sequence: "timeout → timeout → timeout",
    recovery_rate: 39,
    avg_retries: 3.8,
    dominant_cause: "Upstream latency",
    replay_safety: 42,
    action: "Escalate issue",
  },
  {
    id: "fp_signature",
    label: "INVALID_SIGNATURE_CLUSTER",
    sequence: "401 → 401 → 401",
    recovery_rate: 14,
    avg_retries: 3.0,
    dominant_cause: "Key mismatch",
    replay_safety: 21,
    action: "Fix endpoint configuration",
  },
];

export const mockRecommendationsResponse: RecommendationResponse[] = [
  {
    id: "rec_01",
    title: "Endpoint likely rate limited",
    detail: "Retry after 10 minutes and reduce concurrency burst.",
    severity: "warning",
  },
  {
    id: "rec_02",
    title: "Replay unsafe",
    detail: "Event already acknowledged; avoid replay to prevent duplication.",
    severity: "danger",
  },
  {
    id: "rec_03",
    title: "Configuration mismatch detected",
    detail: "Validate secret rotation and webhook signing settings.",
    severity: "info",
  },
];

export const mockReplayAnalysisResponse: ReplayAnalysisResponse = {
  confidence_score: 82,
  duplicate_risk_score: 36,
  unsafe_score: 18,
  confidence_distribution: [
    { band: "Safe", value: 62 },
    { band: "Duplicate Risk", value: 21 },
    { band: "Unsafe", value: 17 },
  ],
  duplicate_risk_distribution: [
    { band: "0-20", value: 6 },
    { band: "21-40", value: 14 },
    { band: "41-60", value: 32 },
    { band: "61-80", value: 22 },
    { band: "81-100", value: 12 },
  ],
};

export const mockRetryOptimizationResponse: RetryOptimizationResponse = {
  decisions: [
    {
      id: "rl_01",
      action: "Retry Now",
      confidence: 86,
      insight: "High likelihood of quick recovery based on recent success.",
      outcome_lift: 14,
    },
    {
      id: "rl_02",
      action: "Delay Retry by 15 Minutes",
      confidence: 72,
      insight: "Rate limits easing in 10-15 minutes.",
      outcome_lift: 9,
    },
    {
      id: "rl_03",
      action: "Stop Retry",
      confidence: 64,
      insight: "Duplicate risk elevated; manual review recommended.",
      outcome_lift: 3,
    },
  ],
  reward_trend: [
    { cycle: "1", reward: 18, success_lift: 6 },
    { cycle: "2", reward: 26, success_lift: 9 },
    { cycle: "3", reward: 34, success_lift: 12 },
    { cycle: "4", reward: 29, success_lift: 10 },
    { cycle: "5", reward: 41, success_lift: 15 },
  ],
};
